# -*- coding: utf-8 -*-
"""24341162_FarhanHaqueShakib_06_Assignement03_Summer2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTFNiAO_UsXeVGycHP50175P2XDe8qRM
"""

values= [3, 6, 2, 3, 7, 1, 2, 0]
def game(d,index, pacman, alpha, beta):
    if(d==3):
        return values[index]

    if(pacman):
        val=float('-inf')
        for i in range(2):
            val2=game(d + 1, index * 2 + i, False, alpha, beta)
            val=max(val,val2)
            alpha=max(alpha,val2)
            if(beta<=alpha):
                break
        return val

    else:
        val=float('inf')
        for i in range(2):
            val2=game(d + 1,index * 2 + i, True, alpha, beta)
            val=min(val,val2)
            beta=min(beta,val2)
            if(beta<=alpha):
                break
        return val

def darkGame(cost):
    S=float('-inf')
    pacman=0
    while(pacman<2):
        ghost=0
        while(ghost<2):
            sc=game(3,pacman*4+ghost, True, float('-inf'), float('inf'))
            S=max(S,sc)
            ghost+= 1
        pacman+=1

    return S-cost

def pacman(cost):
    normal=game(0, 0, True, float('-inf'), float('inf'))
    magic=darkGame(cost)
    if(magic > normal):
        return f"The new minimax value is {magic}. Pacman goes right and uses dark magic"
    else:
        return f"The minimax value is {normal}. Pacman does not use dark magic"

with open("/content/drive/MyDrive/422_lab3(task2)/2434162_FarhanHaqueShakib_CSE422_06_Assignment03_Summer2024_InputFile.txt",'r') as file1:
      n=int(file1.read())
      j=pacman(n)
      with open("/content/drive/MyDrive/422_lab3(task2)/ouput.txt",'w') as file2:
           file2.write(f'{j}')