# -*- coding: utf-8 -*-
"""24341162_FarhanHaqueShakib_06_Assignement03_Summer2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Wd_i5UOsauwPN2zGRLRkdnwig66ABNj
"""

import math
INFINITY = math.inf
class Node:
    def __init__(self, value=None, children=None):
        self.value=value
        if (children is not None):
            self.children=children
        else:
            self.children=[]

    def is_terminal(self):
        return len(self.children)==0

    def evaluate(self):
        return self.value

    def get_children(self):
        return self.children

def main_code(node, depth, alpha, beta, maxP):
    if (depth==0 or node.is_terminal()):
        return node.evaluate()

    if (maxP):
        V = -INFINITY
        for i in node.get_children():
            V=max(V, main_code(i,depth - 1,alpha, beta, False))
            alpha=max(alpha, V)
            if(beta <= alpha):
                break
        return V
    else:
        V=INFINITY
        for i in node.get_children():
            V= min(V, main_code(i,depth - 1,alpha,beta,True))
            beta=min(beta, V)
            if(beta<=alpha):
                break
        return V

def tree(depth):
    if (depth==0):
        n1 = Node(value=-1)
        n2 = Node(value=1)
        lis = [n1, n2]

        return lis

    else:
        children=tree(depth - 1)
        lis = []
        a=2
        while(a):
            new_node = Node(children=children.copy())
            lis.append(new_node)
            a-=1

        return lis

def simulate_battle(s_p):
    Tree = tree(5)
    T=[]
    cP = s_p

    for round_number in range(3):
        rootN = Tree[0]
        depth = 5
        alpha = -INFINITY
        beta = INFINITY
        if(cP==0):
           maxP=1
        else:
           maxP=0

        final=main_code(rootN,depth,alpha,beta,maxP)

        if (final==-1):
            w='Scorpion'
        else:
            w='Sub-Zero'

        T.append(w)
        cP=1-cP

    scorpion_wins=T.count('Scorpion')
    sub_zero_wins=T.count('Sub-Zero')

    if (scorpion_wins > sub_zero_wins):
        W = 'Scorpion'
    else:
        W = 'Sub-Zero'

    return W, len(T),T


with open("/content/drive/MyDrive/422_lab3(task1)/24341162_FarhanHaqueShakib_CSE422_06_Assignment03_Summer2024_InputFile.txt.txt",'r') as file1:
       s_p=int(file1.read())
       winner, total, listWinners = simulate_battle(s_p)
       with open("/content/drive/MyDrive/422_lab3(task1)/output.txt",'w') as file2:
            file2.write(f'Game Winner: {winner}\n')
            file2.write(f'Total Rounds Played: {total}\n')
            for i, round_winner in enumerate(listWinners, start=1):
                file2.write(f'Winner of Round {i}: {round_winner}\n')